version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data

  discovery:
    image: discovery:latest
    restart: always
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10

  gateway:
    image: gateway:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      discovery:
        condition: service_healthy
      registration:
        condition: service_healthy

  registration:
    image: registration:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      discovery:
        condition: service_healthy
      database:
        condition: service_healthy
volumes:
  postgres-data:

