import AdminLayout from '@/components/layout/AdminLayout';
import { ReactNode } from 'react';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/auth_options';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="fr" className="h-full bg-gray-900">
    <body className="h-full text-white">
    <AdminLayout session={session!}>{children}</AdminLayout>
    </body>
    </html>
  );
}
