import AdminLayout from '@/components/layout/AdminLayout';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fr" className="h-full bg-gray-900">
    <body className="h-full text-white">
    <AdminLayout>{children}</AdminLayout>
    </body>
    </html>
  );
}
